

development:
  adapter: postgresql
  encoding: unicode
  database: izvid_dev   # <-- this is the DB you need
  username: niko
  password: novadb
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: izvid_test   # <-- this is the DB you need
  username: niko
  password: novadb
  host: localhost
  database: izvid_test

production: 
  adapter: postgresql
  encoding: unicode
  database: izvid_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
